### ISSUE TITLE
The name 'AVMediaType' does not exist in the current context

### ISSUE THREAD

**Issue by guestDev321** [Redth/ZXing.Net.Maui#10]
After upgrading to Visual Studio 2022 v 17.1.0 Preview 2.0, when compiling the project the following error is seen in ZXing.Net.MAUI/Apple/CameraManager.apple.cs

The name 'AVMediaType' does not exist in the current context

**Comment by julienGrd** [comment]
same problem here. for now i disable targeting IOS and maccatalyst for make it work.

**Comment by guestDev321** [comment]
I need to target iOS, could someone help provide the C# equivalent for using AVCaptureDeviceDiscoverySession? 

See Swift code reference here: 

https://jameshfisher.com/2020/07/31/devicesfor-was-deprecated-in-macos-1015-use-avcapturedevicediscoverysession-instead/

https://stackoverflow.com/questions/44735554/ios-deviceswithmediatype-deprecated

**Comment by julienGrd** [comment]
@guestDev321 do you was able to migrate the code to target ios ?

**Comment by Redth** [comment]
This is fixed since MAUI GA
