### ISSUE TITLE
Is there a Nuget Package for this Library ?

### ISSUE THREAD

**Issue by nssidhu** [Redth/ZXing.Net.Maui#11]
Is there a Nuget Package for this Library ?
Also apart from reading QR Code can this be used to Display QR Code as well or not ?

**Comment by hazwan223** [comment]
Did you manage to get this sample running?

**Comment by nssidhu** [comment]
@hazwan223, No. looks like author is busy or may be this is his personal project that he does not intend to share with public

**Comment by hazwan223** [comment]
> @hazwan223, No. looks like author is busy or may be this is his personal project that he does not intend to share with public

thats a shame. I have no idea what to use as a replacement on my MAUI app

**Comment by nssidhu** [comment]
Not this authors fault. It could just be his personal project.

Sent from Yahoo Mail for iPhone


On Saturday, February 19, 2022, 12:55 PM, hazwan223 ***@***.***> wrote:





@hazwan223, No. looks like author is busy or may be this is his personal project that he does not intend to share with public


thats a shame. I have no idea what to use as a replacement on my MAUI app

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by julienGrd** [comment]
Personnaly i was able to make it works with updates but the problem i have to disable compatibility with IOS

see the problem with IOS here : https://github.com/Redth/BigIslandBarcoding/issues/10

**Comment by julienGrd** [comment]
This package look unmaintain for now

I just create a fork which solve the compilation errors https://github.com/julienGrd/BigIslandBarcoding

i also publish a nuget package ZXing.Net.Maui.Jgdev

this fork don't have vocation to be maintained or used in production, its just to have something which work with the current preview. I wait also for a more maintainable solution, maybe we have to wait for the Release of MAUI

**Comment by Redth** [comment]
Yep there is now.
