### ISSUE TITLE
net8 and Comet

### ISSUE THREAD

**Issue by kfrancis** [Redth/ZXing.Net.Maui#143]
When attempting to use this in net8 RCs, the Comet project is really unhappy. Builds, but when you attempt to run it can't find the handlers for DI.

**Comment by kfrancis** [comment]
Eh, this might be [harder](https://github.com/flyperstudio/Comet/issues/16). Any chance the comet-generated stuff can be replaced with something else?

**Comment by dgerding** [comment]
The _release_ .net8 with "add-net8" branch and .net8 targets etc now builds and runs with Android and Windows devices for me. Can't test Apple platform but interested if anyone has had luck there.

**Comment by kfrancis** [comment]
Yea, the only thing that I needed to do with that branch was not include the comet project - which isn't needed any longer but was still included there. We're using this in net8 just fine now.
