### ISSUE TITLE
Failed to resolve assembly in .Net MAUI

### ISSUE THREAD

**Issue by BryanLow13082018** [Redth/ZXing.Net.Maui#17]
![image](https://user-images.githubusercontent.com/42332748/172369009-efd429a9-602d-46d9-b316-4055744f8f98.png)

I have already added this to the xaml file, but on compilation, this error is thrown:

![image](https://user-images.githubusercontent.com/42332748/172368866-34b1240e-3530-4e83-a894-15d0317fbac0.png)

These are my packages:
![image](https://user-images.githubusercontent.com/42332748/172369370-fb1e74b7-cfcc-4756-8787-78911b3a9479.png)

**Comment by Redth** [comment]
Use the official package.
