### ISSUE TITLE
 How do I check if my app has camera permissions in Windows? 

### ISSUE THREAD

**Issue by VictoriaRamirezCharles** [Redth/ZXing.Net.Maui#170]
When I remove access, this image is automatically placed, but I don't see anything that tells me the status.
![image](https://github.com/Redth/ZXing.Net.Maui/assets/38332341/b9165fe7-9f20-4ed9-bc34-0ab634775465)

I tried to verify the permissions this way but it always returns true.

    public async Task<bool> CheckPermissions()
            => (await Permissions.RequestAsync<Permissions.Camera>()) == PermissionStatus.Granted;

![image](https://github.com/Redth/ZXing.Net.Maui/assets/38332341/485fea29-1120-44e3-a5aa-ccdbdfeb3e5f)

![image](https://github.com/Redth/ZXing.Net.Maui/assets/38332341/6e97723d-d739-4b2d-be0a-2db515f534bb)

**Comment by MitchBomcanhao** [comment]
you can do something like this just on windows

```
using (var mediaCapture = new MediaCapture())
{
    try
    {
        await mediaCapture.InitializeAsync(new MediaCaptureInitializationSettings
        { 
            StreamingCaptureMode = StreamingCaptureMode.Video
        });
        return PermissionStatus.Granted;
    }
    catch (UnauthorizedAccessException)
    {
        return PermissionStatus.Denied;
    }
    catch (Exception)
    {
        return PermissionStatus.Disabled;
    }
}
```

**Comment by VictoriaRamirezCharles** [comment]
> you can do something like this just on windows
> 
> ```
> using (var mediaCapture = new MediaCapture())
> {
>     try
>     {
>         await mediaCapture.InitializeAsync(new MediaCaptureInitializationSettings
>         { 
>             StreamingCaptureMode = StreamingCaptureMode.Video
>         });
>         return PermissionStatus.Granted;
>     }
>     catch (UnauthorizedAccessException)
>     {
>         return PermissionStatus.Denied;
>     }
>     catch (Exception)
>     {
>         return PermissionStatus.Disabled;
>     }
> }
> ```

Thanks!!

**Comment by VictoriaRamirezCharles** [comment]
> you can do something like this just on windows
> 
> ```
> using (var mediaCapture = new MediaCapture())
> {
>     try
>     {
>         await mediaCapture.InitializeAsync(new MediaCaptureInitializationSettings
>         { 
>             StreamingCaptureMode = StreamingCaptureMode.Video
>         });
>         return PermissionStatus.Granted;
>     }
>     catch (UnauthorizedAccessException)
>     {
>         return PermissionStatus.Denied;
>     }
>     catch (Exception)
>     {
>         return PermissionStatus.Disabled;
>     }
> }
> ```
Thanks!!!!
