### ISSUE TITLE
Failed to read QR code.

### ISSUE THREAD

**Issue by czendoo** [Redth/ZXing.Net.Maui#18]
The library can't read / detect the following QR code. I was able to read the code with Goolge Lens app on Android.

![qr-code-err](https://user-images.githubusercontent.com/43118624/173514336-5a93b6da-8c78-4bec-97b1-fc657fa54ea7.jpg)

**Comment by Redth** [comment]
Next preview has a `TryInverted` property in the barcode options which when set to true will allow this inverse colored QR code to be read correctly.

**Comment by czendoo** [comment]
Great, thank you.
