### ISSUE TITLE
If i have to use this in Blazor Hybrid App, How do i use it ?

### ISSUE THREAD

**Issue by nssidhu** [Redth/ZXing.Net.Maui#22]
I am wondering how do i use this in Blazor Hybrid App ?
Any sample code on using Native Controls/Component in Blazor Hybrid?

This is what i tried.

![image](https://user-images.githubusercontent.com/3267605/182983841-1006ede6-4f7a-49d5-97d7-443505ece257.png)

**Comment by Eilon** [comment]
This is not possible. The way to use it would have to have a .NET MAUI XAML page that uses both controls. Something like this:

```xaml
<ContentPage
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    ...>
    <VerticalStackLayout>
        <BlazorWebView ...... />
        <CameraBarcode.... />
    </VerticalStackLayout>
</ContentPage>
```

The BlazorWebView is itself a native .NET MAUI control, so just like you can't put a CameraBarcode inside a .NET MAUI "Label" control, you also cannot put it in a BlazorWebView control.

**Comment by nssidhu** [comment]
@Eilon 
Thanks for clarifying.
Is it possible to have mixed pages (.xaml & .razor) in the Blazor Hybrid?
if possible, how would I navigate between those pages?
In that case, for one-off scenario I would use .xaml page and navigate to that page and back to .razor page
Most of the pages will be .razor to keep it portable so that it can be used on Browser (Blazor WebAssembly).

**Comment by Redth** [comment]
You can have mixed pages definitely, but they have to start with a base of XAML/MAUI and then you can mix in Blazor components through the <BlazorWebView /> XAML Control as @Eilon demonstrated above.

You could navigate between XAML pages in a MAUI app and a XAML page could just be a single <BlazorWebView /> control if you really wanted.

**Comment by Ewerton** [comment]
For those like me and @nssidhu which are using Blazor, here is a possible solution:

1. Create a XAML component to read the barcode following the ZXing documentation
```
<!-- MyCustomBarcodeReader.XAML -->
<zxing:CameraBarcodeReaderView 
            x:Name="barcodeReader"
            WidthRequest="300"
            HeightRequest="300"
            IsDetecting="true" 
            IsTorchOn="false" 
            BarcodesDetected="CameraBarcodeReaderView_BarcodesDetected"   />
```
2.  On the MyCustomBarcodeReader.xaml.cs implement methods to respond to the CameraBarcodeReaderView_BarcodesDetected event, to close your MyCustomBarcodeReader and to emit and new event to the caller when something is read.
```
// Declares an Delegate and a Event to notify callers when a barcode is read
public delegate void BarcodeDetected(string barcodeResult);
public event BarcodeDetected OnBarcodeDetected;
private bool AutomaticCloseOnDetect = true;

... 

// Fired by ZXing when a barcode is read
private void CameraBarcodeReaderView_BarcodesDetected(object sender, ZXing.Net.Maui.BarcodeDetectionEventArgs e)
{
    Dispatcher.Dispatch(() =>
    {
        // Just a debug label
        barcodeResult.Text = $"Barcode: {e.Results[0].Value}      Formato:{e.Results[0].Format}";

        // "Tell the caller that a barcode was detected
        if (OnBarcodeDetected != null)
        {
             // Notify callers that a barcode was read
             OnBarcodeDetected(e.Results[0].Value);

            if (AutomaticCloseOnDetect) // you can pass a parameter to control this behavior
                CloseReader();
        }
    });       
}

... 

// Just a utility function to close your MyCustomBarcodeReader
private void CloseReader()
{
        App.Current.MainPage.Navigation.PopModalAsync(true);
}
```

2.  In the Blazor side, call your shiny new MyCustomBarcodeReader and implement a function to take some action when a barcode is read
```
public void ReadBarcodeButtonClick()
{
    // BarcodeBlazorTest.razor.cs
    MyCustomBarcodeReader barcodeReaderMauiComponent = new MyCustomBarcodeReader();

    // SignUp for the OnBarcodeDetected event to be notified when a new barcode is read
    barcodeReaderMauiComponent.OnBarcodeDetected += BarcodeReaderMauiComponent_OnBarcodeDetected;

    // Opens the Maui XAML Component 
    App.Current.MainPage.Navigation.PushModalAsync(barcodeReaderMauiComponent);
}
...

private string barcodeJustRead; // you can bind it in your .razor --> <h1>@barcodeJustRead</h1>
private void BarcodeReaderMauiComponent_OnBarcodeDetected(string barcodeResult)
{
      barcodeJustRead = barcodeResult
      StateHasChanged();
}
```

Hope this helps.

**Comment by nssidhu** [comment]
Wow! if that is possible it will be great.Will give it a try in few days.


Sent from Yahoo Mail for iPhone


On Wednesday, August 17, 2022, 3:21 PM, Ewerton Mattos ***@***.***> wrote:




For those like me and @nssidhu which are using Blazor, here is a possible solution:
   
   - Create a XAML component to read the barcode following the ZXing documentation

<zxing:CameraBarcodeReaderView 
            x:Name="barcodeReader"
            WidthRequest="300"
            HeightRequest="300"
            IsDetecting="true" 
            IsTorchOn="false" 
            BarcodesDetected="CameraBarcodeReaderView_BarcodesDetected"   />
   
   - On the MyCustomBarcodeReader.xaml.cs implement methods to respond to the CameraBarcodeReaderView_BarcodesDetected event, to close your MyCustomBarcodeReader and to emit and new event to the caller when something is read.
// Declares an Delegate and a Event to notify callers when a barcode is read
public delegate void BarcodeDetected(string barcodeResult);
public event BarcodeDetected OnBarcodeDetected;
private bool AutomaticCloseOnDetect = true;

... 

// Fired by ZXing when a barcode is read
private void CameraBarcodeReaderView_BarcodesDetected(object sender, ZXing.Net.Maui.BarcodeDetectionEventArgs e)
{
    Dispatcher.Dispatch(() =>
    {
        // Just a debug label
        barcodeResult.Text = $"Barcode: {e.Results[0].Value}      Formato:{e.Results[0].Format}";

        // "Tell the caller that a barcode was detected
        if (OnBarcodeDetected != null)
        {
             // Notify callers that a barcode was read
             OnBarcodeDetected(e.Results[0].Value);

            if (AutomaticCloseOnDetect) // you can pass a parameter to control this behavior
                CloseReader();
        }
    });       
}

... 

// Just a utility function to close your MyCustomBarcodeReader
private void CloseReader()
{
        App.Current.MainPage.Navigation.PopModalAsync(true);
}
   
   - In the Blazor side, call your shiny new MyCustomBarcodeReader and implement a function to take some action when a barcode is read
public void ReadBarcodeButtonClick()
{
    // BarcodeBlazorTest.razor.cs
    MyCustomBarcodeReader barcodeReaderMauiComponent = new MyCustomBarcodeReader();

    // SignUp for the OnBarcodeDetected event to be notified when a new barcode is read
    barcodeReaderMauiComponent.OnBarcodeDetected += BarcodeReaderMauiComponent_OnBarcodeDetected;

    // Opens the Maui XAML Component 
    App.Current.MainPage.Navigation.PushModalAsync(barcodeReaderMauiComponent);
}
...

private string barcodeJustRead; // you can bind it in your .razor --> ***@***.***</h1>
private void BarcodeReaderMauiComponent_OnBarcodeDetected(string barcodeResult)
{
      barcodeJustRead = barcodeResult
      StateHasChanged();
}

Hope this helps.
