### ISSUE TITLE
Latest commit (.NET Core #41) not scanning at all on Android 12

### ISSUE THREAD

**Issue by mirza-r** [Redth/ZXing.Net.Maui#24]
Test on Android 12, Pixel 4a

**Comment by infrasoft2007** [comment]
Even with my smartphone, no barcode/qrcode is recognized.
I test on Android 12 and Android 10 the last commited version of BigIslandBarcode sample (0.1.0-preview.3).

**Comment by triadcoders** [comment]
Same, tested with Samsung S22 Ultra.

**Comment by triadcoders** [comment]
If I build with the latest Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.3.0   It is working again.    This update was just recently released to allow Maui Tooling with out using VS preview

**Comment by JakobWl** [comment]
Tested on two different Android 12 Phones and no scanning happened. Visual Studio 2022 17.3.1.

**Comment by jfversluis** [comment]
@JakobWl did you try the workaround I posted? Also does it work if you hold the phone in landscape mode while scanning?

**Comment by JakobWl** [comment]
@jfversluis Yes, I tried the mentioned workaround without success. Also I held the phone in both directions.
```
             builder
	        .UseMauiApp<App>()
		.UseBarcodeReader()
            .ConfigureMauiHandlers(h =>
            {
                h.AddHandler(typeof(CameraBarcodeReaderView), typeof(CameraBarcodeReaderViewHandler));
                h.AddHandler(typeof(CameraView), typeof(CameraViewHandler));
                h.AddHandler(typeof(BarcodeGeneratorView), typeof(BarcodeGeneratorViewHandler));
            })
            .ConfigureFonts(fonts =>
			{
				fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
				fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
			});
```
I even found out that in my case the Decode operation of ZXing.NET always returns null.
```
namespace ZXing.Net.Maui.Readers
...
public BarcodeResult[] Decode(PixelBufferHolder image)
		{
			var w = (int)image.Size.Width;
			var h = (int)image.Size.Height;

			LuminanceSource ls = default;

#if ANDROID
			ls = new ByteBufferYUVLuminanceSource(image.Data, w, h, 0, 0, w, h);
#elif MACCATALYST || IOS
			ls = new CVPixelBufferBGRA32LuminanceSource(image.Data, w, h);
#endif

			if (Options.Multiple)
				return zxingReader.DecodeMultiple(ls)?.ToBarcodeResults();

			var c = zxingReader.Decode(ls); // <== null

			var b = c.ToBarcodeResult();

            if (b != null)
				return new[] { b };

			return null;
		}
```
So ToBarCodeResult() will eventually fail.

**Comment by infrasoft2007** [comment]
I try the last version of code (with the merge request #25), and now the sample BigIslandBarcode can read qrcode correctly :thumbsup:.
Attention, in the BigIslandBarcode sample (on my device), when qrcode is been read, the app print message on output console, but the gui not change.

**Comment by JakobWl** [comment]
@infrasoft2007 For me it works now if your gui is not updating you have to use the dispatcher. If you are already using it there is more information needed.
