### ISSUE TITLE
how to show detecting result  in view

### ISSUE THREAD

**Issue by lingopen** [Redth/ZXing.Net.Maui#30]

**Comment by g0dpain** [comment]
add to the body of the detected-event method following code:

```csharp
Dispatcher.Dispatch(() => {
      barcodeResult.Text = e.Results[0].Value; 
});
```
Where barcodeResult is your text element in your view.
If you want to alert it then do something like this:
``await App.Current.MainPage.DisplayAlert("Barcode result", e.Results[0].Value, "OK");``
