### ISSUE TITLE
How to use in .Net MAUI Blazor (Blazor Hybrid)

### ISSUE THREAD

**Issue by rajeshsws** [Redth/ZXing.Net.Maui#39]
Would be great help if some one can share code how to use in .net maui blazor app(blazor hybrid).
Will Zxing.Net.Maui will support all previous version of android like form 7 onward to 12? or only some specific version.

**Comment by rajeshsws** [comment]
I solved the problem Guys.
Blazor Code
<button class="btn btn-warning" @onclick="Openwindow">Scan Now</button>
@code{


    async Task Openwindow()
    {

        App.Current.MainPage.Navigation.PushModalAsync(new NewPage1());
    }
}
Add a new MAUI Xaml Page 
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="ZXingMAUI.NewPage1"
                     xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI"
             Title="NewPage1">
    <VerticalStackLayout>
        <zxing:CameraBarcodeReaderView x:Name="barcodeReader"  
                                           WidthRequest="300" HeightRequest="300"
                IsDetecting="True" IsTorchOn="False" BarcodesDetected="barcodeReader_BarcodesDetected_1" />

        <Label
                x:Name="barcodeResult"
                Text="Hello, World!"
                SemanticProperties.HeadingLevel="Level1"
                FontSize="32"
                HorizontalOptions="Center" />
        <Button Text="🔄️" Grid.Column="0" BackgroundColor="#aa000000" CornerRadius="8" BorderColor="Black" Clicked="Button_Clicked" />
        
    </VerticalStackLayout>
</ContentPage>

public NewPage1()
	{
		InitializeComponent();
        barcodeReader.Options = new BarcodeReaderOptions
        {
            Formats = BarcodeFormats.OneDimensional,
            AutoRotate = true,
            Multiple = true
        };
    }



	private void barcodeReader_BarcodesDetected_1(object sender, ZXing.Net.Maui.BarcodeDetectionEventArgs e)
	{
        Dispatcher.Dispatch(() =>
        {
            barcodeResult.Text = e.Results[0].Value.ToString();// $"{e.Results[0].Value}";
            Globaclass.BarcodeID = barcodeResult.Text;
            Navigation.PopAsync();
        });
    }

	private void Button_Clicked(object sender, EventArgs e)
	{
        barcodeReader.CameraLocation = barcodeReader.CameraLocation == CameraLocation.Rear ? CameraLocation.Front : CameraLocation.Rear;
    }

and problem solved

**Comment by ragininternet** [comment]
@rajeshsws: I love to do your workaround and implement it. But I can't follow your Code Example. What goes Where? I would be delighted if you could take the time help clear it up.
1. Add in Pages/index.razor:  `<button class="btn btn-warning" @OnClick="Openwindow">Scan Now</button>  ...`
2. ...

Thx you for your time.

**Comment by aryehsilver** [comment]
@ragininternet I've uploaded a quick test app [here](https://github.com/aryehsilver/QRCodeMAUIBlazorTest)

**Comment by Dca91** [comment]
The navigation back ( Navigation.PopAsync(); ) in Xaml page doesn't work, it never comes back to orignal page (blazorview), any idea ? The same with the test app [here](https://github.com/aryehsilver/QRCodeMAUIBlazorTest).

**Comment by Polemus** [comment]
Gerald Versluis has a video doing exactly what you guys are asking:

https://www.youtube.com/watch?v=2dllz4NZC0I&t=6s 

Believe me, i was also struggling for quite a while. 

I've implemented his solution in a .net MAUI Blazor mobile application and it works perfectly.

**Comment by JTOne123** [comment]
Let me give my two cents: https://pavlodatsiuk.hashnode.dev/implementing-maui-blazor-with-zxing-qr-barcode-scanner
