### ISSUE TITLE
Red Line  in the barcode reading - ZXingDefaultOverlay

### ISSUE THREAD

**Issue by MauroAndrePassos** [Redth/ZXing.Net.Maui#45]
Hello guys!

I would like to know how do I put the red line in the barcode reading.

In the ZXing.Net.Mobile.Forms library we have zxing:ZXingDefaultOverlay.

How do I do the same function of showing the red line in the ZXing.Net.MAUI library?

Thanks!

**Comment by Redth** [comment]
Sure, put a view in your page with the control to simulate a red line!
