### ISSUE TITLE
[Bug & Proposal] doesn't work in FlyoutPage & Init and call directly in C#

### ISSUE THREAD

**Issue by SunshineSpring666** [Redth/ZXing.Net.Maui#46]
When put it inside a FlyoutPage, the CameraBarcodeReaderView doesn't show.

We need to put it in a separate page and navigate to it, 
or call it directly in C# (which is way better) like in [ZXing.Net.Mobile](https://github.com/Redth/ZXing.Net.Mobile):

var scanner = new ZXing.Mobile.MobileBarcodeScanner();
var result = await scanner.Scan();
if (result != null)
	Console.WriteLine("Scanned Barcode: " + result.Text);

This FlyoutPage scenario might relates to [#7](https://github.com/Redth/ZXing.Net.Maui/issues/7), which still exists in latest version (Android 10+; iOS not tested).
No workaround found yet.

Also, could you please put the FlipCamera and ToggleTorch as a standard overlay, so as to make the functionalities easier to be called.

Thanks a lot.
Best Regards

**Comment by SunshineSpring666** [comment]
Below is a demo project illustrating the issue:
[maapp.zip](https://github.com/Redth/ZXing.Net.Maui/files/9564036/maapp.zip)

**Comment by nebula2** [comment]
This is basically #7 

Created a PR for this but It has not been approved yet.

**Comment by Redth** [comment]
@nebula2 's PR was brought in, the latest release has the fixes. Thanks!
