### ISSUE TITLE
How to use it in MAUI Blazor project

### ISSUE THREAD

**Issue by idimou** [Redth/ZXing.Net.Maui#47]
After importing the nuget package, adding ```.UseBarcodeReader();``` and adding the namespace to the razor file, once I add the control

```
<CameraBarcodeReaderView x:Name="cameraBarcodeReaderView" BarcodesDetected="BarcodesDetected"  />
```
Visual Studio shows:
"Found markup element with unexpected name."

=> Visual Studio cannot find the control in order to use it in the razor file. 
- Is this a known issue? 
- What's the correct way to use ZXing.Net.Maui in a MAUI Blazor app?

**Comment by ToGz** [comment]
there is small closed issue on this topic: https://github.com/Redth/ZXing.Net.Maui/issues/39.
A takeout is that as a workaround u could simply crate a xaml page invoked from the razor code

**Comment by idimou** [comment]
Many thanks. I'll give it a try. Should have read the issues carefully before opening a new one...

**Comment by aryehsilver** [comment]
@idimou the `CameraBarcodeReaderView` class isn't a Blazor component and can therefore not be used like one. This is why you are getting the error.
I have uploaded a test repo with the suggested solution in #39 which you can find [here](https://github.com/aryehsilver/QRCodeMAUIBlazorTest).
