### ISSUE TITLE
Call barcode reader from code behind

### ISSUE THREAD

**Issue by AndreasReitberger** [Redth/ZXing.Net.Maui#51]
I'm using this library for my Xamarin.Forms apps.
There, I used to get the barcode via following code snippet.

```cs
MobileBarcodeScanner scanner = new()
                    {
                        UseCustomOverlay = false
                    };
                    ZXing.Result result = await scanner.Scan();
                    if (result != null)
                        var myBC = result.Text;
```

How do I achive the same with the MAUI version?
Thanks for helping out!

**Comment by osnipezzini** [comment]
I agree this too, the best thing about old ZXing.Forms are this

**Comment by Redth** [comment]
You don't.  There were a number of issues with how this worked in Xamarin.Forms.

Look at the sample, create a page, use the barcode reader control on the page.  It's a bit more setup but it's not terribly hard.
