### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by Paroca72** [Redth/ZXing.Net.Maui#55]
Hello

After install:
NuGet\Install-Package ZXing.Net.Maui -Version 0.2.0-preview.1

```
using ZXing.Net.Maui;

// ... other code 

public static MauiApp Create()
{
	var builder = MauiApp.CreateBuilder();

	builder
		.UseMauiApp<App>()
		.UseBarcodeReader(); // Make sure to add this line

	return builder.Build();
}
```

After this code I have an error on `UseBarcodeReader`:
'xxxx' does not contain a definition for 'UseBarcodeReader' and no accessible extension method 'UseBarcodeReader' accepting a first argument of type 'xxxx' could be found (are you missing a using directive or an assembly reference?).

In the xaml file after:
`xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI"`

Have an issue on Controls that seems missing.

Very thanks for your support

**Comment by SunshineSpring666** [comment]
Hi everyone,
Same situation encountered here.
Thanks.

**Comment by g0dpain** [comment]
@Redth The new assembly ``ZXing.Net.Maui.Controls`` is missing

@Paroca72 @SunshineSpring666 for the time being you can pull the repo and pack that assembly yourself. Afterwards don't forget to change ``xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI"`` to ``xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI.Controls"``

**Comment by Myina** [comment]
Having the same issue.

**Comment by SunshineSpring666** [comment]
Hi @g0dpain, 
Thanks. This issue still exists in 0.2.0-preview.2 NuGet update.

**Comment by g0dpain** [comment]
@SunshineSpring666 Redth packed the ``ZXing.Net.Maui.Controls`` assembly yesterday, have you downloaded it? Remember to change your xml namespace to ``xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI.Controls"``

**Comment by abecker1** [comment]
Same issue also in Version 0.2.0-preview.1 and Version 0.2.0-preview.2 for me

**Comment by jenscski** [comment]
@abecker1 , you need to install https://www.nuget.org/packages/ZXing.Net.Maui.Controls/0.2.0-preview.2
It's now splitted into two nuget packages, instead of one ...

**Comment by abecker1** [comment]
> @abecker1 , you need to install https://www.nuget.org/packages/ZXing.Net.Maui.Controls/0.2.0-preview.2 It's now splitted into two nuget packages, instead of one ...

Thanks didn't see that it is splitted now

**Comment by SunshineSpring666** [comment]
Thanks @g0dpain, it works now.
