### ISSUE TITLE
App keeps stopping after reading PDF417 barcode and not possible to read Plessey barcode.

### ISSUE THREAD

**Issue by geertgeerits** [Redth/ZXing.Net.Maui#56]
Samsung Galaxy S21 phone Android 12 - ZXing.Net.Maui version 0.1.0-preview.7 - Visual Studio 17.3.6

App keeps stopping after reading PDF417 barcode (9 out of 10).
Also it does not read the Plessey and MaxiCode barcodes.
No problems with reading other barcodes.

Thanks in advance.

**Comment by g0dpain** [comment]
Hi, for type PDF417 please update to version 0.2.0-preview.2. That should fix it.
Also for this version you will have to download ``ZXing.Net.Maui.Controls`` and rename the assembly to ``ZXing.Net.Maui.Controls`` in your zxing-xml namespace if you are using the predefined ScannerView

Don't know about the other two barcode types though, sorry
