### ISSUE TITLE
Missing Namespace 'Controls' in 0.2.0 preview.1

### ISSUE THREAD

**Issue by Myina** [Redth/ZXing.Net.Maui#57]
The 'Controls' Namespace is missing in version 0.2.0 preview.1. I get the following error: 
Error CS0234 The type or namespace name 'Controls' does not exist in the namespace 'ZXing.Net.Maui' (are you missing an assembly reference?).

**Comment by iwilld0it** [comment]
Same here.

**Comment by g0dpain** [comment]
Same as https://github.com/Redth/ZXing.Net.Maui/issues/55
Another library has been published, please try https://github.com/Redth/ZXing.Net.Maui/issues/55#issuecomment-1286516842

**Comment by Myina** [comment]
To solve this problem, upgrade to **ZXing.Net.Maui** 0.2.0-preview.2 and download additional package **ZXing.Net.Maui.Controls** 0.2.0-preview.2. Afterwards, import `using ZXing.Net.Maui.Controls` as required and rebuild.

I feel this might help.
