### ISSUE TITLE
1D barcode only reads in vertical orientation

### ISSUE THREAD

**Issue by guestDev321** [Redth/ZXing.Net.Maui#6]
When scanning 1D barcodes, the camera only reads the barcode when it's in a vertical orientation (rotated vertically). This does not happen with QR codes where camera can pick up any orientation of the QR code. This happens on Android physical device

**Comment by mirza-r** [comment]
I can confirm this issue for me.

I'm currently using the NuGet: ZXing.Net.Maui.Jgdev 1.0.5, Visual Studio 17.3.0 Preview 1.1 and physical devices Pixel 4a-5G, Pixel 3a, Pixel 5.

Also when including the Library as a Project, the same issue can be observed.

I also tried the AutoRotate option with no measurable effects:
```
        cameraBarcodeReaderView.Options = new BarcodeReaderOptions
        {
            Formats = BarcodeFormats.All,
            AutoRotate = true,
            Multiple = false,
	    TryHarder = false,			
        };
```

**Comment by Quietscheente** [comment]
Same for me. But works fine when holding phone in landscape orientation.

**Comment by rogerio-dalvi** [comment]
Hi everyone, I tried to use and have the same impression that just work for 1D barcodes in landscape orientation. But, I aldo tried to read three different barcodes and I can't, either in landscape, then I've download a barcode scanner software and sucess to read.
Anyone uses this library in a commercial application?

**Comment by mirza-r** [comment]
> Hi everyone, I tried to use and have the same impression that just work for 1D barcodes in landscape orientation. But, I aldo tried to read three different barcodes and I can't, either in landscape, then I've download a barcode scanner software and sucess to read. Anyone uses this library in a commercial application?

Many use the Xamarin version of this library, pretty successfully so far.

**Comment by Realinspirer** [comment]
Can confirm.

**Comment by g0dpain** [comment]
See PR https://github.com/Redth/ZXing.Net.Maui/pull/27

**Comment by kajzik** [comment]
After some testing - property ZXingBarcodeReader.Options is set to its default valu in ZXingBarcodeReader.Decode method, AutoRotate is false therefore it does not try rotate image. Same for another settings in BarcodeReaderOptions.

**Comment by Redth** [comment]
This is fixed in the latest preview.  Basically the issue was the barcode reader instance was not being cached and was registered as a transient service so the options never 'stuck'

**Comment by mirza-r** [comment]
Thanks (with a small delay)
