### ISSUE TITLE
Error  when using UseBarcodeReader(); in MauiProgram.cs

### ISSUE THREAD

**Issue by HobDev** [Redth/ZXing.Net.Maui#60]
I was using this package for Barcode scanning. But after update to 0.2.0-preview.2 getting build error. 

`Error	CS1061	'MauiAppBuilder' does not contain a definition for 'UseBarcodeReader' and no accessible extension method 'UseBarcodeReader' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?)	Barcodescanner (net6.0-android), Barcodescanner (net6.0-ios), Barcodescanner (net6.0-maccatalyst), Barcodescanner (net6.0-windows10.0.19041.0)`

[Barcodescanner.zip](https://github.com/Redth/ZXing.Net.Maui/files/9849415/Barcodescanner.zip)

**Comment by HobDev** [comment]
Also getting the below mentioned error on this code `handlers.AddHandler(typeof(ZXing.Net.Maui.Controls.CameraBarcodeReaderView), typeof(CameraBarcodeReaderViewHandler));`

`Error	CS0234	The type or namespace name 'Controls' does not exist in the namespace 'ZXing.Net.Maui' (are you missing an assembly reference?)	Audire (net6.0-android), Audire (net6.0-ios)`

**Comment by g0dpain** [comment]
did you download ZXing.Net.Maui.Controls package?

**Comment by HobDev** [comment]
> did you download ZXing.Net.Maui.Controls package?
> 
> Edit: [Link to nuget](https://www.nuget.org/packages/ZXing.Net.Maui.Controls/0.2.0-preview.2) #55

Thank you. The error disappear after the NuGet installation.
