### ISSUE TITLE
net7.0 support

### ISSUE THREAD

**Issue by sven-s** [Redth/ZXing.Net.Maui#66]
I am trying to use the nuget package with targetframework 7.0 but I am getting the error, it is not compatible with net7.0.

Is there any chance how to use this project under 7.0?

**Comment by softlion** [comment]
I'm able to reference the package in a .net7 project, use it, and compile, no issue.

**Comment by vniehues** [comment]
@sven-s How did you fix your issue? I'm running into the same error.

**Comment by sven-s** [comment]
My problem is, that we are targeting also net7.0 but the projects in this solution are missing the target net7.0 or net6.0. So I cloned the git repo and updated the project files with:

`<TargetFrameworks>net7.0;net7.0-android;net7.0-maccatalyst;net7.0-ios</TargetFrameworks>`

**Comment by vniehues** [comment]
@sven-s Okay that is exactly the same problem that I have. Thanks for the update, I'll go the same route.
