### ISSUE TITLE
Error dotnet 7?

### ISSUE THREAD

**Issue by daveRQ** [Redth/ZXing.Net.Maui#73]
When installing the nuget, and when adding the information in the MauiProgram.cs I get the following error:

Error CS1061 'MauiAppBuilder' does not contain a definition for 'UseBarcodeReader' and no accessible extension method 'UseBarcodeReader' accepting a first argument of type 'MauiAppBuilder' could be found (are you missing a using directive or an assembly reference?) QR (net7 .0-android), QR (net7.0-ios), QR (net7.0-maccatalyst), QR (net7.0-windows10.0.19041.0) E:\QR\QR\MauiProgram.cs 13 Enable

**Comment by managedcoder** [comment]
Ditto!  Dotnet 7 and latest Visual Studio 2022 enterprise and I got the very same error

**Comment by MaximG1234** [comment]
UseBarcodeReader() exists in the ZXing.Net.Maui.Controls namespace, make sure you have the correct nuget package and namespace referenced in your project.

I've got it working fine in .NET 7

**Comment by managedcoder** [comment]
@MaximG1234 , thank you!  I didn't add the ZXing.Net.Maui.Controls library... didn't know I needed to from my reading of the README doc but once I added it and included "using ZXing.Net.Maui.Controls;" I was able to compile

**Comment by g2udevelopment** [comment]
This deserves a pull request on the documentation. Because this is not obvious from the current README
