### ISSUE TITLE
Dotnet 7 

### ISSUE THREAD

**Issue by x71hicks** [Redth/ZXing.Net.Maui#74]
thanks for the contribution, I have problems the library for .NET 7.0 does not recognize me

![imagen](https://user-images.githubusercontent.com/38568359/201699484-5b377495-cff8-4116-bd61-6b36007d4423.png)

**Comment by MaximG1234** [comment]
The correct xaml reference is:

`xmlns:zxing="clr-namespace:ZXing.Net.Maui.Controls;assembly=ZXing.Net.MAUI.Controls"`

**Comment by x71hicks** [comment]
thank you. I had not realized that there is a zxing.net.maui.control package that had to be installed. Now it works along with your indication.
