### ISSUE TITLE
Package ZXing.Net.Maui not recognized

### ISSUE THREAD

**Issue by ArnoSlabbinck** [Redth/ZXing.Net.Maui#78]
Hi, I'm trying to use the ZXing.Net.Maui package to make a barcode scanner on MAUI. I tried to do this with via a tutorial but I get an error in VS 2022 that he can't recognize the package name. Does anybody else have this issue and more importantly does anybody know why this happens and what can be done about it. I need to use this package.
![image](https://user-images.githubusercontent.com/19469941/202860378-35d1aa94-4ccc-4e73-89fa-89b194f5f04d.png)

![image](https://user-images.githubusercontent.com/19469941/202860439-68b29177-73cc-4b27-94e6-91df853e8d8e.png)

![image](https://user-images.githubusercontent.com/19469941/202860458-57d042dc-6723-454a-adda-16ea06745e35.png)

VS doesn't seem to give any underlying red on the names where I use the methods from the package to set up the barcode scanner.

**Comment by x71hicks** [comment]
I install additional package ZXing.Net.Maui.Controls
my problem was solved. I see that zxing doesn't recognize you, it may be the same

**Comment by itldg** [comment]
> I install additional package ZXing.Net.Maui.Controls my problem was solved. I see that zxing doesn't recognize you, it may be the same

This is very helpful to me, thank you

**Comment by renanpaiva64** [comment]
> I install additional package ZXing.Net.Maui.Controls my problem was solved. I see that zxing doesn't recognize you, it may be the same

Thanks, this fix my problem.
