### ISSUE TITLE
How to run on MAUI app

### ISSUE THREAD

**Issue by Kingdom-Of-Heaven** [Redth/ZXing.Net.Maui#9]
I am new to MAUI app, i am trying to run this on my razor page. Can somebody help me out? This is my current code below.
I got error saying that:

`Error (active)	CS0246	The type or namespace name 'BarcodeDetectionEventArgs' could not be found (are you missing a using directive or an assembly reference?)	MauiAppBlazor (net6.0-android)	`

```
@page "/counter"
@using ZXing.Mobile

<zxing:CameraBarcodeReaderView x:Name="cameraBarcodeReaderView"
                               BarcodesDetected="BarcodesDetected" />

@code {
    public void BarcodesDetected(object sender, BarcodeDetectionEventArgs e)
    {
    if (e is null)
    {
        throw new ArgumentNullException(nameof(e));
    }

    foreach (var barcode in e.Results)
        //Console.WriteLine($"Barcodes: {barcode.Format} -> {barcode.Value}");
    }
}

```

**Comment by brendanalexdr** [comment]
bump

**Comment by rajeshsws** [comment]
@using ZXing.Net.Maui

**Comment by Redth** [comment]
Shouldn't be an issue in GA MAUI releases.
