### ISSUE TITLE
UseBarcodeReader not found

### ISSUE THREAD

**Issue by Geronatsios** [Redth/ZXing.Net.Maui#90]
Hi
I just installed Zxing.Net.Maui but UseBarcodeReader() missing

**Comment by aromerom56** [comment]
Hi,
Same issue, ZXing.Net.Maui 0.3.0-preview.1 / dot net 7.0

**Comment by SKIDDOW** [comment]
Add namesapce `using ZXing.Net.Maui.Controls;`

**Comment by Srki94** [comment]
> Install package `ZXing.Net.Maui.Controls` Then add namesapce `using ZXing.Net.Maui.Controls;`

For anyone having this issue, the package is in prerelease, thus won't show in the default VS NuGet search until you check the "Prerelease". 

P.S. Thanks.
