### ISSUE TITLE
How to specify multiple barcode types without using BarcodeFormats.All

### ISSUE THREAD

**Issue by Quaybe** [Redth/ZXing.Net.Maui#97]
Hello,

This may be because I still have some big knowledge gaps in C#, but I can't seem to figure out how to make this scan for only 2 or 3 barcode types without having it scan for all barcode types, slowing performance.

Is there a way I can just enable Code128 and QR, for example?

My current code is similar to the example in the ReadMe:

```
cameraBarcodeReaderView.Options = new BarcodeReaderOptions
        {
            Formats = BarcodeFormats.All, Multiple = false, AutoRotate = true, TryInverted = true
        };
```
How can I tell it to just do Code128 and QR?

**Comment by Ghostbird** [comment]
The Formats setting is a [bit field](https://en.wikipedia.org/wiki/Bit_field) in C# called [bit flags](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/enum#enumeration-types-as-bit-flags).
You can combine any of the definitions from [BarcodeFormat.cs](../blob/main/ZXing.Net.MAUI/BarcodeFormat.cs) using the [bitwise or operator](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/bitwise-and-shift-operators#enumeration-logical-operators)

### Example

```csharp
var barcodeReaderView = new CameraBarcodeReaderView
{
  Options = new BarcodeReaderOptions
  {
    Formats = BarcodeFormat.CODE_128 | BarcodeFormat.QrCode
  }
} 
```

**Comment by Quaybe** [comment]
Thank you so much! That makes sense. I genuinely appreciate the help as I'm working on a big project that is likely going to rely on this feature.
