### ISSUE TITLE
Microsoft.Maui.Platform.HandlerNotFoundException:** 'Handler not found for view ZXing.Net.Maui.Controls.CameraBarcodeReaderView.

### ISSUE THREAD

**Issue by JORGEGO** [Redth/ZXing.Net.Maui#98]
Microsoft.Maui.Platform.HandlerNotFoundException:** 'Handler not found for view ZXing.Net.Maui.Controls.CameraBarcodeReaderView.

Last version produce this exception.

Please could tell me when you will have a version 1.0

It is important for my current migration from all my apps working Xamarin.Forms with Zxing

Thanks

**Comment by sikandaramla** [comment]
Add handler details in the MauiProgram.cs file:

builder
            .UseMauiApp<App>()
            .UseBarcodeReader()
            .ConfigureMauiHandlers(h =>
            {
                h.AddHandler(typeof(ZXing.Net.Maui.Controls.CameraBarcodeReaderView), 
                    typeof(CameraBarcodeReaderViewHandler));
                h.AddHandler(typeof(ZXing.Net.Maui.Controls.CameraView),
                    typeof(CameraViewHandler));
                h.AddHandler(typeof(ZXing.Net.Maui.Controls.BarcodeGeneratorView),
                    typeof(BarcodeGeneratorViewHandler));
            });

**Comment by JORGEGO** [comment]
I have added those lines and nothing...
![Screenshot_20230115_191318](https://user-images.githubusercontent.com/3842104/212559323-4047aea2-3425-4e7b-b8a4-7f2cd0af8909.jpg)

**Comment by JORGEGO** [comment]
> Add handler details in the MauiProgram.cs file:
> 
> builder .UseMauiApp() .UseBarcodeReader() .ConfigureMauiHandlers(h => { h.AddHandler(typeof(ZXing.Net.Maui.Controls.CameraBarcodeReaderView), typeof(CameraBarcodeReaderViewHandler)); h.AddHandler(typeof(ZXing.Net.Maui.Controls.CameraView), typeof(CameraViewHandler)); h.AddHandler(typeof(ZXing.Net.Maui.Controls.BarcodeGeneratorView), typeof(BarcodeGeneratorViewHandler)); });

It works!!!!
